title: Harlan Kellaway is a cool developer
short_title: harlankellaway.com
url: http://harlankellaway.com
description: Harlan Kellaway is a developer

handle_github: hkellaway
handle_twitter: HarlanKellaway
handle_disqus: hkellaway-dev
url_email_subscription: https://feedburner.google.com/fb/a/mailverify?uri=harlan-kellaway-blog

highlighter: rouge
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
exclude: ['.git']
