title: Harlan Kellaway is a cool developer
url: http://harlankellaway.com
description: Thoughts on development.

handle_github: hkellaway
handle_twitter: HarlanKellaway
url_email_subscription: https://feedburner.google.com/fb/a/mailverify?uri=hkellaway-dev

highlighter: true
permalink: /:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Otter Pop"
description: Harlan Kellaway, developer
url: http://hkellaway.github.o
