title: Harlan Kellaway is a cool developer
short_title: harlankellaway.com
url: http://harlankellaway.com
description: Thoughts on development.

handle_github: hkellaway
handle_twitter: HarlanKellaway
handle_disqus: hkellaway-dev
url_email_subscription: https://feedburner.google.com/fb/a/mailverify?uri=hkellaway-dev

highlighter: true
permalink: /blog/:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Harlan Kellaway"
description: Harlan Kellaway, developer
url: http://hkellaway.github.o

gems:
  - jekyll-sitemap
