title: Harlan Kellaway codes
short_title: hkellaway.github.io
url: https://hkellaway.github.io
description: Harlan Kellaway is a software engineer specializing in iOS

handle_github: hkellaway
handle_twitter: HarlanKellaway
handle_disqus: hkellaway-dev
url_email_subscription: https://feedburner.google.com/fb/a/mailverify?uri=harlan-kellaway-blog

highlighter: rouge
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
exclude: ['.git']
