title: Harlan Kellaway is a cool developer
handle_github: hkellaway
handle_twitter: HarlanKellaway

highlighter: true
permalink: /:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Otter Pop"
description: Harlan Kellaway, developer
url: http://hkellaway.github.o
